### PR TITLE
[FIX] Incorrect call to email validator from python-validators

### PR DESCRIPTION
**Pull request by dempstert**
The existing code raises an error as it is illegal syntax.

### CODE REVIEW

**Comment by tvuotila** [comment]
@dempstert Can you update the `setup.py` to require `validators>=0.21`. That is the version where the email validator function signature changed.

**Comment by dempstert** [comment]
@tvuotila It's already specified as `validators>=0.5.0`

**Comment by tvuotila** [comment]
The `validators` package seems to require Python 3 since version 0.14.3. Thus, this change would make `wtforms-components` to drop Python 2.7 support.
@kvesteri What do you think about dropping Python 2 support?

**Comment by kvesteri** [comment]
Yep it's fine to drop py27 support

**Comment by tvuotila** [comment]
I just noticed that you are treating the whitelist like it would be a blacklist.

**Comment by jpvanhal** [comment]
Closing since the whitelist argument was removed in #75.

**Pull request closed without merging**
